apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-monitoring
  namespace: monitoring
  labels:
    app: nginx-monitoring
spec:
  selector:
    matchLabels:
      monitoring: "true"  # Выбираем сервисы с этой меткой
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics