apiVersion: v1
kind: ServiceAccount
metadata:
  name: cd
  namespace: homework
---
# RoleBinding для предоставления admin прав в namespace homework
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cd-admin
  namespace: homework
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin  # Используем встроенную ClusterRole admin
subjects:
- kind: ServiceAccount
  name: cd
  namespace: homework