# external-secrets-values.yaml
# Конфигурация для External Secrets Operator

replicaCount: 1

image:
  repository: ghcr.io/external-secrets/external-secrets
  pullPolicy: IfNotPresent

installCRDs: true

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

# Webhook конфигурация
webhook:
  replicaCount: 1

  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 256Mi

# Cert controller
certController:
  replicaCount: 1

  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 256Mi

# Метрики
metrics:
  enabled: true
  service:
    enabled: true

# RBAC
rbac:
  create: true

serviceAccount:
  create: true
  name: external-secrets

# Namespace для установки
namespace: vault