# external-secret.yaml
# ExternalSecret для получения секретов из Vault

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: otus-cred
  namespace: vault
spec:
  # Интервал обновления секрета
  refreshInterval: 15s

  # Ссылка на SecretStore
  secretStoreRef:
    name: vault-backend
    kind: SecretStore

  # Целевой Secret, который будет создан
  target:
    name: otus-cred
    creationPolicy: Owner

  # Данные для извлечения из Vault
  data:
    - secretKey: username
      remoteRef:
        key: cred
        property: username

    - secretKey: password
      remoteRef:
        key: cred
        property: password