apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: webserver
    release: {{ .Release.Name }}
data:
  {{- range $key, $value := .Values.configData }}
  {{ $key }}: |
{{ $value | indent 4 }}
  {{- end }}