apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: homework-storage
provisioner: k8s.io/minikube-hostpath
reclaimPolicy: Retain  # PV не будет удален при удалении PVC
volumeBindingMode: Immediate
allowVolumeExpansion: true