apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mysql-operator-minimal
  namespace: homework
rules:
# Права на управление CRD MySQL в namespace homework
- apiGroups: ["otus.homework"]
  resources: ["mysqls"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["otus.homework"]
  resources: ["mysqls/status"]
  verbs: ["get", "update", "patch"]
- apiGroups: ["otus.homework"]
  resources: ["mysqls/finalizers"]
  verbs: ["update"]

# Права на создание/управление Deployments
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

# Права на создание/управление Services
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

# Права на создание/управление PersistentVolumeClaims
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

# Права на создание Events для логирования
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]

# Права на чтение ConfigMaps для конфигурации оператора
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
---
# RoleBinding вместо ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mysql-operator-minimal
  namespace: homework
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mysql-operator-minimal
subjects:
- kind: ServiceAccount
  name: mysql-operator
  namespace: homework
---
# ClusterRole только для PV (они кластерные)
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mysql-operator-pv
rules:
- apiGroups: [""]
  resources: ["persistentvolumes"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
# ClusterRoleBinding для PV
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mysql-operator-pv
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mysql-operator-pv
subjects:
- kind: ServiceAccount
  name: mysql-operator
  namespace: homework