apiVersion: v1
kind: Pod
metadata:
  name: webserver-pod
  namespace: homework
spec:
  volumes:
    - name: shared-data
      emptyDir: {}  # Общий том для обмена данными между контейнерами
  initContainers:
    - name: init-container
      image: busybox:latest
      command:
        - wget
        - "-O"
        - "/init/index.html"
        - http://info.cern.ch
      volumeMounts:
        - name: shared-data
          mountPath: /init  # Монтируем общий том в директорию /init
  containers:
    - name: webserver-container
      image: python:3.8-alpine
      ports:
        - containerPort: 8000
      lifecycle:
        preStop:
          exec:
            command: ["rm", "-f", "/homework/index.html"]
      command:
        - sh
        - -c
        - |
          # Запускаем веб-сервер на 8000 порту, отдающий содержимое директории /homework
          python -m http.server 8000 --directory /homework
      volumeMounts:
        - name: shared-data
          mountPath: /homework  # Монтируем общий том в директорию /homework
